name: Mule CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  JAVA_VERSION: '17'
  MAVEN_VERSION: '3.9.6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - name: Checkout mule-libs Repository
        uses: actions/checkout@v4
        with:
          repository: davidsantana1103/mule-libs
          path: mule-libs

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Install Maven ${{ env.MAVEN_VERSION }}
        run: |
          MAVEN_URL="https://dlcdn.apache.org/maven/maven-3/${{ env.MAVEN_VERSION }}/binaries/apache-maven-${{ env.MAVEN_VERSION }}-bin.tar.gz"
          wget $MAVEN_URL
          tar -xvzf apache-maven-${{ env.MAVEN_VERSION }}-bin.tar.gz
          sudo mv apache-maven-${{ env.MAVEN_VERSION }} /opt/maven
          echo "M2_HOME=/opt/maven" >> $GITHUB_ENV
          echo "/opt/maven/bin" >> $GITHUB_PATH

      - name: Verify Maven Version
        run: mvn -v
        
      - name: Configure Maven Settings
        run: |
          mkdir -p settings
          cat > settings/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>${{ secrets.MULE_USERNAME }}</username>
                <password>${{ secrets.MULE_PASSWORD }}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>local-maven-repo</id>
                <mirrorOf>*</mirrorOf>
                <url>file://$(pwd)/mule-libs/</url>
                <layout>default</layout>
              </mirror>
            </mirrors>
          </settings>
          EOF

      - name: Build Mule Application with Maven
        run: |
          mvn clean package \
            -Dmaven.repo.local=$(pwd)/mule-libs/\
            -s settings/settings.xml

      - name: Upload Mule Artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: mule-app
          path: target/*.jar

